### ISSUE TITLE
Emailing Later

### ISSUE THREAD

**Issue by tehstun** [CodeDoesGood/MercuryBack#96]
When the email service is down, all emails should be pushed with content into a file or database that will be loaded on reset or status change of the email client. If there is content in the file, email the content.

#### File Content

```js
{
    emails: [{
        from: "sending address",
        html: "content",
        subject: "subject",
        text: "content",
        to: "receiver"
    }],
}
```

## Todo

- [x] Create the file and data flow used for emailing people after the service comes back up from an outage.
- [x] Email creation middleware creation before checking online status, allowing us to store the emails if the service is down.
- [x] Integrate middleware to handle storing of the data
- [x] Messages should be sent to the debug webhook instead of production when production is false in the .env file.
- [x] A way to update the email client to attempt to bring it back up after an offline or down related error occurs / a way to trigger the restart of the service as well.
- [x] Endpoints for Administrators to restart the service
- [x] Admins with portal access should be able to see any emails unable to be sent or retry any or all emails from the panel.
- [x] Endpoint for administrators to update the service
- [x] Admins should be able to remove late stored emails by index / id.
- [x] Admins should be able to update late stored emails by index / id.
- [x] Write tests to cover all new email client component functions
- [x] Relook over the newly written code before creating the pull request

## Bugs
- [x] Emails being removed should be removed by index otherwise the wrong emails are left if one fails to send.

## Extra

- [x] Talk to project leaders about moving the failed to send emails into the database instead of a json file. Which would later be accessed to send when the service is online. @swiftcode what do you think about this?

- [x] The email sending flow might have to be async or delayed due to bulk emailing causing blacklisting?

**Comment by tehstun** [comment]
On startup the system will now check the stored email file that will contain all the late emails ̣(unable to be sent), and attempt to resend them all.

Next step would be the middleware that would be used to update the stored file with the late emails, I think this should be moved to the database in a new table. Instead of a file.

**Comment by swiftcode** [comment]
I'm fine with storing them in a database and processing the transactions in chronological order 
when the system comes back up.  The JSON doesn't have a datetime stamp, but that's OK if we stamp the record when it's created in the DB.  Will having a date/time of the last attempt (to send) be useful or just extra baggage that we don't need? 

Are you planning to create a new table for unsent emails?  Or, create a flag in the current table?

**Comment by tehstun** [comment]
Last attempt time stamping is good as we can see if for any reason there are emails attempting to be sent that is not going through but we currently do not even have a table that refers to any type of email.

Do you know of the table you where thinking of or?
